# Generated by Django 6.1 on 2026-08-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universityclasses',
            old_name='instructor_number',
            new_name='instructor_name',
        ),
    ]
